### ISSUE TITLE
regression/sat.4.cnf

### ISSUE THREAD

**Issue by ntp890517** [ntp890517/sat#1]
Call stack:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b4492f in std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) where
#0  0x00007ffff7b4492f in std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000404e29 in std::list<ImplicationGraphNode*, std::allocator<ImplicationGraphNode*> >::_M_insert<ImplicationGraphNode* const&> (this=0x6190b0, __position=)
    at /usr/include/c++/4.8/bits/stl_list.h:1562
#2  0x0000000000404a7e in std::list<ImplicationGraphNode*, std::allocator<ImplicationGraphNode*> >::push_back (this=0x6190b0, __x=@0x7fffffffe290: 0x61c5b0)
    at /usr/include/c++/4.8/bits/stl_list.h:1016
#3  0x0000000000404881 in ImplicationGraphEdge::AddInNode (this=0x619098, n=0x61c5b0) at src/db/ImplicationGraph.h:67
#4  0x000000000040418d in ImplicationGraph::Conflict (this=0x619058, n1=0x61c5b0, n2=0x61c560) at src/db/ImplicationGraph.cpp:22
#5  0x00000000004076a7 in SolverDPLL::BCP (this=0x619010, assign=0x61b870) at src/sol/SolverDPLL.cpp:173
#6  0x0000000000406db3 in SolverDPLL::Solve (this=0x619010) at src/sol/SolverDPLL.cpp:53
#7  0x0000000000402211 in main ()
```

**Comment by ntp890517** [comment]
Recompiled. Seems it stuck in infinite loop.

**Comment by ntp890517** [comment]
Resolve crash and fix bug by sat.4.shrink.cnf.
Put sat.4.shrink.cnf to regression case.
